class DeviceType:
    EXTINGUISHER = "EXTINGUISHER"
    HYDRANT = "HYDRANT"
    SMOKE_DETECTOR = "SMOKE_DETECTOR"
    SPRINKLER = "SPRINKLER"
    EXIT_LIGHT = "EXIT_LIGHT"
    ALL = (EXTINGUISHER, HYDRANT, SMOKE_DETECTOR, SPRINKLER, EXIT_LIGHT)


# 兼容旧引用
DeviceTypeList = list(DeviceType.ALL)
