class ErrorCode:
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    RBAC_DENIED = "RBAC_DENIED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    NOT_FOUND = "NOT_FOUND"
    STATE_CONFLICT = "STATE_CONFLICT"
    STALE_TASK_REVISION = "STALE_TASK_REVISION"
    REVIEWED_PROTECTED = "REVIEWED_PROTECTED"
    REVIEW_TARGET_INVALID = "REVIEW_TARGET_INVALID"
    CHECKLIST_ITEM_INVALID = "CHECKLIST_ITEM_INVALID"
    HAZARD_NOT_OPEN = "HAZARD_NOT_OPEN"
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_CODES = {
    "AUTH_REQUIRED": ErrorCode.AUTH_REQUIRED,
    "AUTH_INVALID": ErrorCode.AUTH_INVALID,
    "RBAC_DENIED": ErrorCode.RBAC_DENIED,
    "VALIDATION_FAILED": ErrorCode.VALIDATION_FAILED,
    "NOT_FOUND": ErrorCode.NOT_FOUND,
    "STATE_CONFLICT": ErrorCode.STATE_CONFLICT,
    "STALE_TASK_REVISION": ErrorCode.STALE_TASK_REVISION,
    "REVIEWED_PROTECTED": ErrorCode.REVIEWED_PROTECTED,
    "REVIEW_TARGET_INVALID": ErrorCode.REVIEW_TARGET_INVALID,
    "CHECKLIST_ITEM_INVALID": ErrorCode.CHECKLIST_ITEM_INVALID,
    "HAZARD_NOT_OPEN": ErrorCode.HAZARD_NOT_OPEN,
    "RATE_LIMITED": ErrorCode.RATE_LIMITED,
    "INTERNAL_ERROR": ErrorCode.INTERNAL_ERROR,
}
