ERROR_CODES = {
  "AUTH_REQUIRED": "AUTH_REQUIRED",
  "RBAC_DENIED": "RBAC_DENIED",
  "VALIDATION_FAILED": "VALIDATION_FAILED",
  "NOT_FOUND": "NOT_FOUND",
  "REVISION_CONFLICT": "REVISION_CONFLICT",
  "TASK_NOT_EDITABLE": "TASK_NOT_EDITABLE",
  "RESULT_LOCKED": "RESULT_LOCKED",
  "HAZARD_STILL_OPEN": "HAZARD_STILL_OPEN"
}
