InspectionStatus = ["PLANNED","IN_PROGRESS","SUBMITTED","REVIEWED","OVERDUE"]
# 只有这些状态下允许巡检员提交/重提交复核链
TASK_SUBMITTABLE_STATUSES = ["PLANNED","IN_PROGRESS","OVERDUE"]
# 已提交/已复核的任务冻结，禁止覆盖结果
TASK_FROZEN_STATUSES = ["SUBMITTED","REVIEWED"]
