class ConflictReason:
    """提交冲突区原因。"""

    STALE_TASK_REVISION = "STALE_TASK_REVISION"
    REVIEWED_PROTECTED = "REVIEWED_PROTECTED"
    ALL = (STALE_TASK_REVISION, REVIEWED_PROTECTED)


class SubmissionState:
    ACCEPTED = "ACCEPTED"
    PARTIAL = "PARTIAL"
    CONFLICT = "CONFLICT"
    REPLAYED = "REPLAYED"
